disabled_rules:
  - inclusive_language
  - function_parameter_count
  - closure_parameter_position

opt_in_rules:
  - anyobject_protocol
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - deployment_target
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_xctest_method
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - single_test_class
  - unused_import
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

line_length: 140
file_length: 800
closure_body_length: 50
function_body_length: 100

type_name:
  min_length: 3
  max_length:
    warning: 50

identifier_name:
  min_length:
    warning: 3
  max_length:
    warning: 50
  excluded:
    - id

force_cast: warning
force_try: warning

deployment_target:
  iOS_deployment_target: 12.0
  
nesting:
  type_level:
    warning: 2

warning_threshold: 1

excluded:
  - GAFoundationTests
  - GAFoundation/FeatureToggleService/FeatureToggleKey.swift
